# Spring Boot Application Name
spring.application.name=Triad-Activities

# Database Configuration
# Using h2 easier to acess
# This works without PostgreSQL
spring.datasource.url=jdbc:h2:mem:triad_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#  Use PostgreSQL 
# spring.datasource.url=${SPRING_DATASOURCE_URL}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA / HIBERNATE CONFIGURATION
# ddl-auto: update = automatically creates/updates tables
spring.jpa.hibernate.ddl-auto=update

# Tell Hibernate we're using H2 database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Show SQL queries in the console / debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 console shows database in browser
# Enable H2 web console at: http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# FREEMARKER CONFIGURATION
# Tell Spring to look for .ftlh files in templates folder
spring.freemarker.suffix=.ftlh
spring.freemarker.template-loader-path=classpath:/templates/

# Logging Configuration for terminal
# Shows SQL queries
logging.level.org.hibernate.SQL=DEBUG
# Shows parameter values in queries
logging.level.org.hibernate.orm.jdbc.bind=TRACE