# Spring Boot Application Properties
spring.application.name=Triad-Activities

# Database Configuration Neon

# Neon PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://ep-flat-math-atx9cdi9-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dFgupait1zC7
spring.datasource.driverClassName=org.postgresql.Driver

# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update

# Tell Hibernate we're using PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Show SQL queries in the console/ debugging
spring.jpa.properties.hibernate.format_sql=true

# FREEMARKER CONFIGURATION

# Tell Spring to look for .ftlh files in templates folder
spring.freemarker.suffix=.ftlh
spring.freemarker.template-loader-path=classpath:/templates/

# LOGGING shows SQL in terminal for debugging purposes

# Shows SQL queries
logging.level.org.hibernate.SQL=DEBUG
# Shows parameter values in queries
logging.level.org.hibernate.orm.jdbc.bind=TRACE